PHASE_WORD_MAPPING = {
    "Main Menu": [
        "Esc.",
        "LIGHT",
        "Auto",
        "Manual",
        "Wiper/Elevator Control",
        "Select Build",
        "Open Door",
        "Service",
        "Heater",
        "Log In/Out",
        "EMERGENCY STOP OPERATED!"
    ],

    "Log In/Out": [
        "Esc.",
        "Log In/Out",
        "Press Here to Log In",
        "Log Out",
        "User Logged In",
    ],

    "Auto Operation": [
        "Esc.",
        "Auto Operation",
        "LIGHT",
        "View",
        "Parameters",
        "Wiper Home Requested",
        "Remaining Build Time",
        "Oxygen Level 1 (Bottom)",
        "Chamber Pressure",
        "Build Height",
        "Max. Build",
        "Pause at Layer",
        "Thickness",
        "Layer No. Pv",
        "No. of Layers",
        "Heater",
        "PV",
        "SP",
        "Dosing",
        "NORMAL",
        "O2 Target",
        "LASER KEYSWITCH OFF!",
    ],

    "Machine Status": [
        "Esc.",
        "Machine Status",
        "Oxygen Level 1 (Bottom)",
        "Oxygen Level 2 (Top)",
        "Slice Preview",
        "Temp Trends",
        "Argon Pressure",
        "Chamber Pressure",
        "mBar",
        "Vacuum Chamber Temperature",
        "Electronics Temperature",
        "Chilled Water Temperature",
        "Optical Train Temperature",
        "Elevator Temperature",
    ],

    "Semi-Auto Chamber Preparation": [
        "Esc.",
        "Semi-Auto Chamber Preparation",
        "LIGHT",
        "View Parameters",
        "Semi Auto Chamber Prep Inactive.",
        "SEMI-AUTO CHAMBER PREP",
        "WITH VACUUM",
        "WITHOUT VACCUM",
        "O2 ppm Target",
        "Duration",
        "LASER KEYSWITCH OFF!"
    ],

    "Manual Control": [
        "Manual Control",
        "View Parameters",
        "STOP",
        "START",
        "OFF",
        "ON",
        "CLOSE",
        "OPEN",
        "Esc.",
        "LIGHT",
        "Semi-Auto Prep",
        "ENABLE MANUAL",
        "Heater",
        "PV",
        "SP",
        "Oxygen Level 1",
        "Chamber Pressure",
        "Gas Valve",
        "Vent Valve",
        "Vacuum Pump",
        "Open Door",
        "Recirc Pump",
        "Not Ready For Manual Operation",
        "EMERGENCY STOP OPERATED!",
        "ppm",
        "mBar"
    ],

    "Wiper/Elevator Position": [
        "Esc.",
        "Wiper/Elevator Position",
        "LIGHT",
        "FIND WIPER HOME",
        "HOME",
        "GO TO FWD. POS",
        "GO TO CENTRE",
        "WIPER AUTO",
        "DOSE",
        "FIND TABLE HOME",
        "LOWER POS",
        "GO TO TOP POS",
        "ABSOLUTE TOP POS",
        "TABLE AUTO",
        "SET DATUM",
        "Build Height",
        "Z-Absolute Position",
        "Substrate Thickness",
        "Thickness",
        "STOP ALL",
        "OPEN DOOR",
        "LASER KEYSWITCH OFF!"
    ],

    "Chamber Door Control": [
        "Esc.",
        "LIGHT",
        "Chamber Pressure",
        "Vacuum Chamber Temperature",
        "Elevator Temperature",
        "DOOR INTERLOCK OVERRIDE DISABLED",
        "Manual Control",
        "Wiper/Elevator Control",
        "EMERGENCY STOP OPERATED!"
        "OVERRIDE ENABLED",
        "Hold Reset Button to enable door opening."
    ],
    "Build Names": [
        "Esc.",
        "Build Names",
        "RESET",
        "EMERGENCY STOP OPERATED!"
    ]
}

# WORD_PHASE_MAPPING = {
#     "Auto Operation": "Auto Operation",
#     "Build Names": "Build Names",
#     "Chamber Pressure": "Chamber Door Control",
#     "Machine Status": "Machine Status",
#     "Manual Control": "Manual Control",
#     "Semi-Auto Chamber Preparation": "Semi-Auto Chamber Preparation",
#     "Wiper/Elevator Position": "Wiper/Elevator Position",
#     "Set Time And Date": "Set Time And Date",
#     "Servo Control Addresses": "Servo Control Addresses",
#     "Alarm/Event History": "Servo Control Addresses",
#     "Alarm/Events": "Alarm/Events",
#     "Elevator Heater": "Alarm/Events",
#     "User Settings": "User Settings",
#     "PC Power Control": "PC Power Control",
#     "RBV Settings": "RBV Settings",
#     "System Tests": "System Tests",
# }
